#!/usr/bin/perl -w

# XXX: How the interrupt numbers are created;
#      Interesting
#      see the content of the vector.S
#     
#      vector222:
#      push $0
#      push $222
#      jmp alltraps
#      vector223:
#      push $0
#      push $223
#      jmp alltraps
#
#      so all the vector address instructions are just pushing
#      the trapnumber then jump to alltraps in trapasm.S
#
#      where before jumping to the trap() is makes rest of the
#      trapframe by pusing the general-purpose registers


# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print "# generated by vectors.pl - do not edit\n";
print "# handlers\n";
print ".global alltraps\n";
for(my $i = 0; $i < 256; $i++){
    # print ".global vector$i\n"; # might be useful for debugging
    print "vector$i:\n";
    if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
        print "  push \$0\n";
    }
    print "  push \$$i\n";
    print "  jmp alltraps\n";
}

print "\n# vector table\n";
print ".data\n";
print ".global vectors\n";
print "vectors:\n";
for(my $i = 0; $i < 256; $i++){
    print "  .quad vector$i\n";
}
